IPS = {central:        '192.168.50.10',
       central_seg1_1: '172.24.4.10',
       worker1:        '192.168.50.100',
       worker1_seg1_1: '172.24.4.100',
       worker2:        '192.168.50.101',
       worker2_seg2_1: '172.24.6.101',
       worker3:        '192.168.50.102',
       worker3_seg2_1: '172.24.6.102',
       iprouter:       '192.168.50.20',
      }


Vagrant.configure(2) do |config|

    config.ssh.forward_agent = true
    config.vm.hostname = "ovnhost"
    config.vm.box = "bento/ubuntu-24.04"
    config.vm.synced_folder './', '/vagrant', type: 'rsync'

    # central as controller node (northd/southd) and as compute connected to segment-1-1
    config.vm.define 'central' do |central|
        central.vm.network 'private_network', ip: IPS[:central]
        central.vm.network 'private_network',
            ip: IPS[:central_seg1_1],
            libvirt__network_name: "segment-1-1-net",
            libvirt__iface_name: "central-s1-1"
        central.vm.hostname = 'central'
        central.vm.provider 'libvirt' do |lb|
            lb.nested = true
            lb.memory = 8192
            lb.cpus = 8
            lb.suspend_mode = 'managedsave'
        end
        central.vm.provision :shell do |shell|
            shell.privileged = false
            shell.path = 'central.sh'
            shell.env = IPS
            shell.args = ['segment-1-1']
        end
    end

    # openstack compute connected to segment-1-1
    config.vm.define 'worker1' do |worker1|
        worker1.vm.network 'private_network', ip: IPS[:worker1]
        worker1.vm.network 'private_network',
            ip: IPS[:worker1_seg1_1],
            libvirt__network_name: "segment-1-1-net",
            libvirt__iface_name: "worker1-s1-1"
        worker1.vm.hostname = 'worker1'
        worker1.vm.provider 'libvirt' do |lb|
            lb.nested = true
            lb.memory = 4096
            lb.cpus = 4
            lb.suspend_mode = 'managedsave'
        end
        worker1.vm.provision :shell do |shell|
            shell.privileged = false
            shell.path = 'worker.sh'
            shell.env = IPS
            shell.args = ['segment-1-1']
        end
    end

    # openstack compute connected to segment-2-1
    config.vm.define 'worker2' do |worker2|
        worker2.vm.network 'private_network', ip: IPS[:worker2]
        worker2.vm.network 'private_network',
            ip: IPS[:worker2_seg2_1],
            libvirt__network_name: "segment-2-1-net",
            libvirt__iface_name: "worker2-s2-1"
        worker2.vm.hostname = 'worker2'
        worker2.vm.provider 'libvirt' do |lb|
            lb.nested = true
            lb.memory = 4096
            lb.cpus = 4
            lb.suspend_mode = 'managedsave'
        end
        worker2.vm.provision :shell do |shell|
            shell.privileged = false
            shell.path = 'worker.sh'
            shell.env = IPS
            shell.args = ['segment-2-1']
        end
    end

    # openstack compute connected to segment-2-1
    config.vm.define 'worker3' do |worker3|
        worker3.vm.network 'private_network', ip: IPS[:worker3]
        worker3.vm.network 'private_network',
            ip: IPS[:worker3_seg2_1],
            libvirt__network_name: "segment-2-1-net",
            libvirt__iface_name: "worker3-s2-1"
        worker3.vm.hostname = 'worker3'
        worker3.vm.provider 'libvirt' do |lb|
            lb.nested = true
            lb.memory = 4096
            lb.cpus = 4
            lb.suspend_mode = 'managedsave'
        end
        worker3.vm.provision :shell do |shell|
            shell.privileged = false
            shell.path = 'worker.sh'
            shell.env = IPS
            shell.args = ['segment-2-1']
        end
    end

    # router between segment-1-1 and segment-2-1
    config.vm.define 'iprouter' do |iprouter|
        iprouter.vm.network 'private_network', ip: IPS[:iprouter]
        iprouter.vm.network 'private_network',
            type: "dhcp",
            auto_config: false,
            libvirt__network_name: "segment-1-1-net",
            libvirt__iface_name: "iprouter-s1-1"
        iprouter.vm.network 'private_network',
            type: "dhcp",
            auto_config: false,
            libvirt__network_name: "segment-2-1-net",
            libvirt__iface_name: "iprouter-s2-1"
        iprouter.vm.hostname = 'iprouter'
        iprouter.vm.provider 'libvirt' do |lb|
            lb.nested = true
            lb.memory = 2048
            lb.cpus = 4
            lb.suspend_mode = 'managedsave'
        end
        iprouter.vm.provision :shell do |shell|
            shell.privileged = false
            shell.path = 'iprouter.sh'
        end
    end

end
